DocumentosPerdidos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from AppDocumentosPerdidos.views import Main

urlpatterns = [
    path('', Main,),
    path('admin/', admin.site.urls),
    path('DocumentosPerdidos/', include('AppDocumentosPerdidos.urls')),
    path('DocumentosPerdidos/', include('UserCoder.urls')),
    path('DocumentosPerdidos/', include('Mensajes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Mensajes/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from Mensajes.views import *

app_name='Mensajes'

urlpatterns = [
    path('Mensaje/BuscarVer/', mensaje_buscar_ver, name='MensajeBuscarVer'),
    path('Mensaje/Ver/<int:id_mensaje>', mensaje_ver, name='MensajeVer'),
    path('Mensaje/Enviar/<str:username>', mensaje_crear, name='MensajeEnviar'),
]

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% include 'styles/styles.html' %}
    <!-- Bloque para cargar el titulo del encabezado-->
    {% block headertitlle %}
    {% endblock %}
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico"/>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'AppCode/css/styles.css' %}" rel="stylesheet"/>
    {% block stile %}
    {% endblock %}
</head>
<body>
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand">Compartiendo opiniones</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="/DocumentosPerdidos">Home</a>
                </li>
                <div class="space">
                </div>
                {% if request.user.is_authenticated %}
                {% if request.user.avatar.avatar.url != "" %}
                <img src="{{ request.user.avatar.avatar.url }}" alt="" width="40px" height="40px">
                {% else %}
                <td class="tddata"></td>
                {% endif %}
                <div class="space">
                </div>
                <a style="color:white;" href="{% url 'UsuariosModificar' user.username %}"> User: <br>
                    {{ user.get_username }}</a>
                <div class="space">
                </div>
                <li class="nav-item"><a class="nav-link active" aria-current="page"
                                        href="{% url 'Mensajes:MensajeBuscarVer' %}">Ver mis mensajes</a>
                </li>
                {% endif %}
                {% block bodytitleoptions %}
                {% endblock %}
                <div class="space">
                </div>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="/admin">Django Admin</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Header-->
<!-- Bloque para cargar la primera seccion de la pagina-->
<header class="bodyheader">
    <div class="container px-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-8">
                {% block bodyheader %}
                {% endblock %}
            </div>
        </div>
    </div>
</header>
<!-- Features section-->
<!-- Bloque para cargar la segunda seccion de la pagina-->
{% block bodyoptions %}
{% endblock %}
<!-- Contact section-->
{% block bodycontact %}
{% endblock %}
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container px-5"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'AppCode/js/scripts.js' %}"></script>
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<!-- * *                               SB Forms JS                               * *-->
<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>