DocumentosPerdidos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from AppDocumentosPerdidos.views import Main

urlpatterns = [
    path('', Main,),
    path('admin/', admin.site.urls),
    path('DocumentosPerdidos/', include('AppDocumentosPerdidos.urls')),
    path('DocumentosPerdidos/', include('UserCoder.urls')),
    path('DocumentosPerdidos/', include('Mensajes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Mensajes/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from Mensajes.views import *

app_name='Mensajes'

urlpatterns = [
    path('Mensaje/BuscarVer/', mensaje_buscar_ver, name='MensajeBuscarVer'),
    path('Mensaje/Ver/<int:id_mensaje>', mensaje_ver, name='MensajeVer'),
    path('Mensaje/Enviar/<str:username>', mensaje_crear, name='MensajeEnviar'),
]

Mensajes/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User


class Mensajes(models.Model):
    id_mensaje = models.AutoField(primary_key=True)
    usuario_origen = models.CharField(max_length=50)
    usuario_destino = models.CharField(max_length=50)
    mensaje = RichTextField(blank=True, null=True)
    fecha_creacion_mensaje = models.DateTimeField(auto_now_add=True)

Mensajes/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget

class DateImput(forms.DateInput):
    input_type = 'date'


class Mensajes_Form(forms.Form):
    mensaje = forms.CharField(widget=CKEditorWidget())

class Buscar_Mensajes_Form(forms.Form):
    usuario_origen = forms.CharField(max_length=50)
    usuario_destino = forms.CharField(max_length=50)
    mensaje = forms.CharField(max_length=50)

Mensajes/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from Mensajes.forms import Mensajes_Form, Buscar_Mensajes_Form
from Mensajes.models import Mensajes
from django.contrib import messages


@login_required()
def mensaje_crear(request, username):
    mensaje = Mensajes_Form(request.POST)
    usernameOrigen = request.user.username
    if request.method == 'POST':
        if mensaje.is_valid():
            mensaje = Mensajes(
                usuario_origen=usernameOrigen,
                usuario_destino=username,
                mensaje=request.POST.get('mensaje'),
            )
            mensaje.save()
            messages.info(request, 'El mensaje se ha enviado con exito!')
        else:
            messages.info(request, 'El mensaje no se ha enviado con exito!')

    contexto = {
        'formularioenviarmensaje': Mensajes_Form(),
        'usuariodestino': username,
    }
    return render(request, 'Mensajes/mensajeenviar.html', contexto)

@login_required()
def mensaje_buscar_ver(request):
    a_buscar = []
    if request.method == 'POST':
        usuarioLogueado = request.user.username
        usuarioorigen = request.POST.get('usuario_origen')
        usuariodestino= request.POST.get('usuario_destino')
        mensaje = request.POST.get('mensaje')

        a_buscar = (Mensajes.objects.filter(usuario_origen=usuarioLogueado) | \
                   Mensajes.objects.filter(usuario_destino=usuarioLogueado)) & \
                   Mensajes.objects.filter(mensaje__icontains=mensaje) & \
                   Mensajes.objects.filter(usuario_origen__icontains=usuarioorigen) & \
                   Mensajes.objects.filter(usuario_destino__icontains=usuariodestino)

    contexto = {
        'buscar_mensaje': Buscar_Mensajes_Form(),
        'mensaje': a_buscar,
    }
    return render(request, 'Mensajes/mensajebuscarver.html', contexto)

@login_required()
def mensaje_ver(request, id_mensaje):
    mensaje = Mensajes.objects.get(id_mensaje=id_mensaje)
    mensaje_form = Mensajes_Form(initial={
        'usuario_origen': mensaje.usuario_origen,
        'usuario_destino': mensaje.usuario_destino,
        'mensaje': mensaje.mensaje,
        'fecha_creacion_mensaje': mensaje.fecha_creacion_mensaje,
    }
    )
    contexto = {
        'formulariomostrarmensaje': mensaje_form,
        'mensaje': mensaje,
    }

    return render(request, 'Mensajes/mensajever.html', contexto)

templates/Mensajes/mensajebuscarver.html
{% extends "index.html" %}

{% block headertitlle %}
<title>Mensajes</title>
{% endblock %}

{% block stile %}
<style>

</style>
{% endblock %}

{% block bodytitleoptions %}
{% if user.is_authenticated %}
<a class="btn btn-primary" href="{% url 'UserCoderLogOut' %}"> Logout </a>
{% endif %}
{% endblock %}

{% block bodyheader %}
<h1 style="color:white; display:inline;">Cargue los datos que desea buscar</h1>
{% endblock %}
{% block bodyoptions %}
<section>
    <div class="datos-documento">
        <div class="container px-5 my-5">
            <div class="row gx-5">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <form class="bodyoptionstittle" method="post" novalidate>{% csrf_token %}
                    <table style="width:30%">
                        {% for field in buscar_mensaje %}
                        <tr>
                            {% if field.label == "Usuario origen" %}
                            <th>Usuario origen:</th>
                            {% endif %}
                            {% if field.label == "Usuario destino" %}
                            <th>Usuario destino:</th>
                            {% endif %}
                            {% if field.label == "Mensaje" %}
                            <th>Mensaje:</th>
                            {% endif %}
                            <th>{{ field }}</th>
                        </tr>
                        {% endfor %}
                    </table>
                    <br>
                    <input style="width: auto;" type="submit" value="Buscar">
                </form>
            </div>
        </div>
    </div>
</section>


<section class="py-5 border-bottom" id="resultado">
    <div class="datos-documento">
        <h4>Los datos encontrados son: </h4>
        <table class="tabledata" style="width:100%; table-layout: fixed">
            {{ formulariomostrarmensaje.media }}
            <tr>
                <th class="thdata">Usuario de</th>
                <th class="thdata">Usuario para</th>
                <th class="thdata">Mensaje</th>
                <th class="thdata">Fecha de creacion</th>
                <th class="thdata">Ver</th>
                <th class="thdata">Responder</th>
            </tr>
            {% for mensaje in mensaje %}
            <tr>
                <td class="tddatacenter">{{mensaje.usuario_origen}}</td>
                <td class="tddatacenter">{{mensaje.usuario_destino}}</td>
                <td class="tddataleft">{{mensaje.mensaje|safe}}</td>
                <td class="tddataleft">{{mensaje.fecha_creacion_mensaje}}</td>
                <td class="tddatacenter"><a
                        href="{% url 'Mensajes:MensajeVer' mensaje.id_mensaje %}">Ver</a></td>
                <td class="tddatacenter"><a
                        href="{% url 'Mensajes:MensajeEnviar' mensaje.usuario_origen %}">Responder</a></td>
            </tr>
            {% endfor %}

        </table>
    </div>
</section>
{% endblock %}

templates/Mensajes/mensajeenviar.html
{% extends "index.html" %}
{% include 'styles/styles.html' %}

{% block headertitlle %}
<title>Envio Mensaje</title>
{% endblock %}

{% block bodytitleoptions %}
{% if user.is_authenticated %}
<a class="btn btn-primary" href="{% url 'UserCoderLogOut' %}"> Logout </a>
{% endif %}
{% endblock %}

{% block bodyheader %}
<h1 class="display-5 fw-bolder text-white mb-2">Enviemos un mensaje</h1>
<div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
</div>
{% endblock %}

{% block bodyoptions %}
<div class="space2">
</div>
<div class="container px-5 my-5">
    <div class="row gx-5">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <form class="bodyoptionstittle" action="{% url 'Mensajes:MensajeEnviar' usuariodestino %}" method="post">{% csrf_token %}
            <table style="width:100%">
                <tr>
                    <th>Usuario destino: </th>
                    <td>{{usuariodestino}}</td>
                </tr>
                <tr>
                    <th>Mensaje: </th>
                    <td>{{formularioenviarmensaje.mensaje}}</td>
                </tr>
                    <th>{{ formularioenviarmensaje.media }}</th>
            </table>
            <br>
            <p><input type="submit" value="Enviar"/></p>
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/Mensajes/mensajever.html
{% extends "index.html" %}

{% block headertitlle %}
<title>Mensajes</title>
{% endblock %}

{% block bodytitleoptions %}
{% if user.is_authenticated %}
<a class="btn btn-primary" href="{% url 'UserCoderLogOut' %}"> Logout </a>
{% endif %}
{% endblock %}

{% block bodyheader %}

<h1 class="display-5 fw-bolder text-white mb-2">Mensaje seleccionado</h1>
<div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
</div>
{% endblock %}
{% block bodyoptions %}
<section>
    <div class="datos-usuario">
        <div class="container px-5 my-5">
            <div class="row gx-5">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <form class="bodyoptionstittle" action="" method="post" enctype="multipart/form-data" novalidate>
                    {%csrf_token %}
                    <table style="width:100%">
                        {{ formularioenviarmensaje.media }}
                        <tr>
                            <th class="thdata">Mensaje de</th>
                            <td class="tddatacenter">{{mensaje.usuario_origen}}</td>
                        </tr>
                        <tr>
                            <th class="thdata">Mensaje</th>
                            <td class="tddatacenter">{{mensaje.mensaje|safe}}</td>
                        </tr>
                        <tr>
                            <th class="thdata">Fecha de creacion</th>
                            <td class="tddatacenter">{{mensaje.fecha_creacion_mensaje}}</td>
                        </tr>
                    </table>
                </form>
            </div>
                <a class="btn btn-primary" href="{% url 'Mensajes:MensajeEnviar' mensaje.usuario_origen %}"> Responder mensaje</a>
        </div>
    </div>

</section>
{% endblock %}